default:
  #--------------------------------------------------------------------------------------------------------------------
  # Setting path and local variables
  #--------------------------------------------------------------------------------------------------------------------
  # v1) Set the study name and abbreviation
  studyName: "Data Quality Assessments on Synthetic Data"
  
  # v2) Set the Name of your center 
  organizationName: "UMG"
  
  # v3) Set the path to input data 
  dataPath: "./data/medData/syntheticData.csv"
  
  # v4) Set the code list of missing data values
  missingCode: !expr list ("",NA, "NULL")
  
  # v5) Specify the path to the spreadsheet file containing the DQ rules
  rulePath: "./data/refData/dqRules.xlsx"
  
  # v6) Set the path to the semantic annotations
  semanticPath: "./data/refData/semData.csv"
  
  # v7) Specify the path to the resulting visualizations and reports
  exportPath: "./data/export"

